name = "shorescoa-survey"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "shorescoa_survey"
database_id = "fb0ffd00-e81a-405b-b7d7-677d23b1cb7c"
